---
title: "Models for DHS heatwave research"
author: "Jade"
date: "2024-01-20"
output: html_document
---

package
```{r}
library(survival)
library(splines)
library(dplyr)
library(tidyr)
library(stringr)
library(mgcv)
```

define mother id
```{r}
childw <- childw %>% mutate(id = paste0(ccphase, caseid, m.bir.cmc))

childwp <- childwp %>% mutate(id = paste0(ccphase, caseid, m.bir.cmc))

pregw <- pregw %>% mutate(id = paste0(ccphase, caseid, m.bir.cmc))
```

main models
```{r}
mf <- c("Surv(rep(1, nrow(childw)), death) ~ hwd95 + t2m + rh + tp + m.age + c.age2 + as.factor(twin2) + as.factor(c.sex) + pm25 + pm10 + co + so2 + no2 + ns(c.bir.y, df = 5) + as.factor(season) + ns(bord, df = 5) + strata(id)", 
        "Surv(rep(1, nrow(childw)), death) ~ hwd90 + t2m + rh + tp + m.age + c.age2 + as.factor(twin2) + as.factor(c.sex) + pm25 + pm10 + co + so2 + no2 + ns(c.bir.y, df = 5) + as.factor(season) + ns(bord, df = 5) + strata(id)", 
        "Surv(rep(1, nrow(childw)), death) ~ hwd92 + t2m + rh + tp + m.age + c.age2 + as.factor(twin2) + as.factor(c.sex) + pm25 + pm10 + co + so2 + no2 + ns(c.bir.y, df = 5) + as.factor(season) + ns(bord, df = 5) + strata(id)", 
        "Surv(rep(1, nrow(childw)), death) ~ hwd97 + t2m + rh + tp + m.age + c.age2 + as.factor(twin2) + as.factor(c.sex) + pm25 + pm10 + co + so2 + no2 + ns(c.bir.y, df = 5) + as.factor(season) + ns(bord, df = 5) + strata(id)")

names(mf) = c("ml95","ml90","ml92","ml97")

mcoef = list()
for(i in 1:length(mf)) {
  f <- mf[i]
  m <- coxph(as.formula(f),data = childw)
  
  coef = summary(m)$coefficients %>%
  as.data.frame() %>%
  mutate(up = exp(coef+1.96*`se(coef)`), 
         low = exp(coef-1.96*`se(coef)`)) %>%
  rename(risk = `exp(coef)`, p = `Pr(>|z|)`) %>%
  dplyr::select(risk, low, up, p)
  
  coef$model=names(which(mf==f))
  coef <- coef[1:13,]
  mcoef[[i]] <- coef
  }

mcoef <- do.call(rbind, mcoef) %>% 
  mutate(hw = substr(model, start = 3, stop = 4), 
         mtype = substr(model, start = 1, stop = 2))

write.csv(mcoef, "E:/Jade/DHS-heat/result/mcoef.csv")
```

interaction models
```{r}
intf <- c("Surv(rep(1, nrow(childwp)), death) ~ hwd95*phwp95 + t2m + rh + tp + m.age + c.age2 + as.factor(twin2) + as.factor(c.sex) + pm25 + pm10 + co + so2 + no2 + ns(c.bir.y, df = 5) + as.factor(season) + ns(bord, df = 5) + strata(id)", 
        "Surv(rep(1, nrow(childwp)), death) ~ hwd90*phwp90 + t2m + rh + tp + m.age + c.age2 + as.factor(twin2) + as.factor(c.sex) + pm25 + pm10 + co + so2 + no2 + ns(c.bir.y, df = 5) + as.factor(season) + ns(bord, df = 5) + strata(id)", 
        "Surv(rep(1, nrow(childwp)), death) ~ hwd92*phwp92 + t2m + rh + tp + m.age + c.age2 + as.factor(twin2) + as.factor(c.sex) + pm25 + pm10 + co + so2 + no2 + ns(c.bir.y, df = 5) + as.factor(season) + ns(bord, df = 5) + strata(id)", 
        "Surv(rep(1, nrow(childwp)), death) ~ hwd97*phwp97 + t2m + rh + tp + m.age + c.age2 + as.factor(twin2) + as.factor(c.sex) + pm25 + pm10 + co + so2 + no2 + ns(c.bir.y, df = 5) + as.factor(season) + ns(bord, df = 5) + strata(id)")

names(intf) = c("il95","il90","il92", "il97")

icoef = list()
ipred = list()
for(i in 1:length(intf)) {
  f <- intf[i]
  m <- coxph(as.formula(f),data = childwp)
  
  coef = summary(m)$coefficients %>% 
    as.data.frame() %>% 
    dplyr::select(1:3,5) %>%
    slice(1:14,30) %>%
    mutate(up = exp(coef+1.96*`se(coef)`), 
           low = exp(coef-1.96*`se(coef)`)) %>%
    rename(risk = `exp(coef)`, p = `Pr(>|z|)`) %>%
    dplyr::select(coef, risk, low, up, p)
  
  vcov = vcov(m) %>%
    as.data.frame() %>%
    dplyr::select(1, 30) %>%
    slice(1, 30)
  
  coef$model=names(which(intf==f))
  icoef[[i]] <- coef
  
  pred <- seq(0, 110, by = 1) %>% as.data.frame()
  colnames(pred) = 'hwd'
  pred$phwd = 1-(pred$hwd/273)
  pred$risk = exp(coef[1,1] + pred$phwd*coef[15,1])
  pred$up = exp(coef[1,1] + pred$phwd*coef[15,1]
                +1.96*sqrt(vcov[1,1]+ vcov[2,2]+2*vcov[1,2]))
  pred$low = exp(coef[1,1] + pred$phwd*coef[15,1]
                 -1.96*sqrt(vcov[1,1]+ vcov[2,2]+2*vcov[1,2]))
  pred$model=names(which(intf==f))
  ipred[[i]] <- pred
}

icoef <- do.call(rbind, icoef) %>% 
  mutate(hw = substr(model, start = 3, stop = 4), 
         mtype = substr(model, start = 1, stop = 2))

ipred <- do.call(rbind, ipred) %>% 
  mutate(hw = substr(model, start = 3, stop = 4), 
         mtype = substr(model, start = 1, stop = 2))

write.csv(icoef, "E:/Jade/DHS-heat/result/icoef.csv")
```

nonlinear models
```{r}
ths <- c("90", "92", "95", "97")

npred <- list()
for (th in ths) {
  hwdv <- paste0("hwd", th)
  phwpv <- paste0("phwp", th)
  
  bn <- gam(as.formula(paste("death ~ te(", hwdv, ",", phwpv, ", k=3)")), 
            data = childwp, method = 'REML', family = binomial(link = "logit"))
  
  bs <- predict(bn, newdata = childwp, type = 'lpmatrix')
  
  newdata <- expand.grid(var1 = seq(0, 30, length.out = 301), 
                         var2 = seq(quantile(childwp[[phwpv]], probs = 0.001), 1, length.out = 301))
  names(newdata) <- c(hwdv, phwpv)
  
  f <- paste("Surv(rep(1, nrow(childwp)), death) ~", 
                       paste(paste0("`", colnames(bs)[2:9], "`"), collapse = "+"), "+",
                       "c.age2 + m.age + as.factor(c.sex) + as.factor(twin2) + ns(bord, df = 5) + t2m + rh + tp + pm25 + pm10 + so2 + no2 + co + ns(c.bir.y, df = 5) + as.factor(season) + strata(id)")
  
  m <- coxph(as.formula(f), data = cbind(childwp, bs))
  
  b <- coef(m)
  b <- b[1:8]
  
  bsn <- predict(bn, newdata = newdata, type = 'lpmatrix')
  bsn <- bsn[,-1]
  
  OR <- exp(bsn %*% b)
  
  fn <- cbind(newdata, OR)
  
  npred[[th]] <- fn
}
```

interaction models: by gender
```{r}
ths = c("90","92","95", "97")
sx = c("M","F")

ipred_sx = list()
icoef_sx = list()
for (th in ths) {
  
  f <- paste0("Surv(rep(1, nrow(childwp)), death) ~ as.factor(c.sex):hwd", th,
                "*phwp", th, " + m.age + c.age2 + as.factor(twin2) + as.factor(c.sex)+ ",
                "t2m + rh + tp + pm10 + no2 + co + pm25 + so2 +",
                "ns(c.bir.y, df = 5) + as.factor(season) + ns(bord, df = 5) + ",
                "strata(id)")
    
  msx <- coxph(as.formula(f), data = childwp)
  
  sxpred = list()
  sxcoef = list()  
  for (i in seq_along(sx)) {
    
    coef = summary(msx)$coefficients %>% 
      as.data.frame() %>% 
      dplyr::select(1,2,5) %>%
      slice(28+i, 30+i)
    
    coef$sx = sx[i]
    coef$th = th
    sxcoef[[i]] <- coef
    
    vcov = vcov(msx) %>%
      as.data.frame() %>%
      dplyr::select(28+i, 30+i) %>%
      slice(28+i, 30+i)

    pred <- seq(0, 110, by = 1) %>% as.data.frame()
    colnames(pred) = 'hwd'
    pred$phwd = 1-(pred$hwd/273)
    pred$risk = exp(coef[1,1] + pred$phwd*coef[2,1])
    pred$up = exp(coef[1,1] + pred$phwd*coef[2,1]
                  +1.96*sqrt(vcov[1,1]+ vcov[2,2]+2*vcov[1,2]))
    pred$low = exp(coef[1,1] + pred$phwd*coef[2,1]
                   -1.96*sqrt(vcov[1,1]+ vcov[2,2]+2*vcov[1,2]))
    pred$sx = sx[i]
    pred$th = th
    sxpred[[i]] <- pred
  }
    icoef_sx[[th]] <- sxcoef
    ipred_sx[[th]] <- sxpred
}
```

interaction models: by mean MHWF
```{r}
mhw90 <- hwd %>%
  filter(th == 90, hwd >= 14) %>%
  group_by(DHSID) %>%
  dplyr::summarise(n90 = n()) 

mhw92 <- hwd %>%
  filter(th == 92, hwd >= 11) %>%
  group_by(DHSID) %>%
  dplyr::summarise(n92 = n()) 

mhw95 <- hwd %>%
  filter(th == 95, hwd >= 7) %>%
  group_by(DHSID) %>%
  dplyr::summarise(n95 = n()) 

mhw97 <- hwd %>%
  filter(th == 97, hwd >= 4) %>%
  group_by(DHSID) %>%
  dplyr::summarise(n97 = n())

childwp <- childwp %>%
  left_join(mhw90, by = "DHSID") %>%
  mutate(nhwd90 = if_else(n90>20, "Y","N")) %>%
  left_join(mhw92, by = "DHSID") %>%
  mutate(nhwd92 = if_else(n92>20, "Y","N")) %>%
  left_join(mhw95, by = "DHSID") %>%
  mutate(nhwd95 = if_else(n95>20, "Y","N")) %>%
  left_join(mhw97, by = "DHSID") %>%
  mutate(nhwd97 = if_else(n97>20, "Y","N"))

hw = c("N","Y")
ths = c("90","92","95", "97")

ipred_hw = list()
icoef_hw = list()
for (th in ths) {
  
  f <- paste0("Surv(rep(1, nrow(childwp)), death) ~ as.factor(nhwd", th, "):hwd", th,
                "*phwp", th, " + m.age + c.age2 + as.factor(twin2) + as.factor(c.sex)+ ",
                "t2m + rh + tp + pm10 + no2 + co + pm25 + so2 +",
                "ns(c.bir.y, df = 5) + as.factor(season) + ns(bord, df = 5) + ",
                "strata(id)")
    
  mhw <- coxph(as.formula(f), data = childwp)
  
  hwpred = list()
  hwcoef = list()  
  for (i in seq_along(hw)) {
    
    coef = summary(mhw)$coefficients %>% 
      as.data.frame() %>% 
      dplyr::select(1,2,5) %>%
      slice(28+i, 30+i)
    
    coef$hw = hw[i]
    coef$th = th
    hwcoef[[i]] <- coef
    
    vcov = vcov(mhw) %>%
      as.data.frame() %>%
      dplyr::select(28+i, 30+i) %>%
      slice(28+i, 30+i)

    pred <- seq(0, 110, by = 1) %>% as.data.frame()
    colnames(pred) = 'hwd'
    pred$phwd = 1-(pred$hwd/273)
    pred$risk = exp(coef[1,1] + pred$phwd*coef[2,1])
    pred$up = exp(coef[1,1] + pred$phwd*coef[2,1]
                  +1.96*sqrt(vcov[1,1]+ vcov[2,2]+2*vcov[1,2]))
    pred$low = exp(coef[1,1] + pred$phwd*coef[2,1]
                   -1.96*sqrt(vcov[1,1]+ vcov[2,2]+2*vcov[1,2]))
    pred$hw = hw[i]
    pred$th = th
    hwpred[[i]] <- pred
  }
    icoef_hw[[th]] <- hwcoef
    ipred_hw[[th]] <- hwpred
}
```

pregnancy loss
```{r}
pregw$pm2 = if_else(pregw$pm >= 5, 1, 0)

vars <- c("hwd95", "hwd97")

ppred <- list()
for (var in vars) {
  
  f <- as.formula(paste0("Surv(rep(1,nrow(pregw)), ploss) ~ bs(", var, ", degree = 3) + t2m + rh + tp + m.age + pm25 + pm10 + co + so2 + no2 + 
  ns(f.y, df = 5) + as.factor(season) + as.factor(pm2) + 
  strata(id)"))
  
  m <- coxph(f, pregw)
  
  coef = summary(m)$coefficients %>%
  as.data.frame() %>%
  mutate(up = coef+1.96*`se(coef)`, 
         low = coef-1.96*`se(coef)`) %>%
  dplyr::rename(risk = coef, p = `Pr(>|z|)`) %>%
  dplyr::select(risk, low, up, p) 
  
  newdata <- seq(0, 30, length.out = 301)
  
  bs <- bs(newdata, degree = 3)
  
  pred <- exp(bs %*% coef[1:3,1])
  
  pd <- data.frame(var = newdata, pred = as.vector(pred))
  names(pd)[1] <- "hwd"
  pd$th <- substr(var, start = 4, stop = 5)
  pd$low <- as.vector(exp(bs %*% coef[1:3,2]))
  pd$up <- as.vector(exp(bs %*% coef[1:3,3]))
  
  ppred[[var]] <- pd
}
```

